# Generated by Django 6.0.7 on 2026-09-10 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExclusaoImagemPendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=255, unique=True)),
                ('motivo', models.CharField(choices=[('substituida', 'Substituída por outra imagem'), ('removida', 'Removida pelo usuário'), ('excluida', 'Objeto excluído'), ('upload_descartado', 'Upload que não chegou ao banco')], max_length=32)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('ultimo_erro', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Exclusão de imagem pendente',
                'verbose_name_plural': 'Exclusões de imagem pendentes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AjusteImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('campo', models.CharField(max_length=64)),
                ('dados', models.JSONField(default=dict)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Ajuste de imagem',
                'verbose_name_plural': 'Ajustes de imagem',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='midia_ajuste_objeto_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'campo'), name='midia_ajuste_unico_por_campo')],
            },
        ),
    ]
