# Generated by Django 6.0.6 on 2026-06-30 00:56

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(blank=True, max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoArmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('comum', models.TextField(blank=True)),
                ('trabalhado', models.TextField(blank=True)),
                ('obra_prima', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('custo', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Foto')),
                ('banner', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Banner')),
                ('nome', models.CharField(db_index=True, max_length=100)),
                ('nivel', models.PositiveIntegerField(default=1)),
                ('idade', models.CharField(blank=True, max_length=10, null=True)),
                ('origem', models.CharField(blank=True, max_length=50, null=True)),
                ('raca', models.CharField(blank=True, max_length=50, null=True)),
                ('classe1', models.CharField(choices=[('combatente', 'Combatente'), ('especialista', 'Especialista'), ('conjurador', 'Conjurador')], default='combatente', max_length=40)),
                ('classe2', models.CharField(choices=[('combatente', 'Combatente'), ('especialista', 'Especialista'), ('conjurador', 'Conjurador')], default='combatente', max_length=40)),
                ('classe3', models.CharField(choices=[('combatente', 'Combatente'), ('especialista', 'Especialista'), ('conjurador', 'Conjurador')], default='combatente', max_length=40)),
                ('classe4', models.CharField(choices=[('combatente', 'Combatente'), ('especialista', 'Especialista'), ('conjurador', 'Conjurador')], default='combatente', max_length=40)),
                ('dinheiro', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('anotacoes', models.TextField(blank=True)),
                ('aparencia', models.TextField(blank=True)),
                ('personalidade', models.TextField(blank=True)),
                ('historia', models.TextField(blank=True)),
                ('relacionamentos', models.TextField(blank=True)),
                ('objetivos', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pericia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('treinamento', models.IntegerField(choices=[(0, 'Sem Treinamento'), (2, '+2'), (4, '+4'), (6, '+6'), (8, '+8'), (10, '+10')], default=0)),
                ('atributo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pericias', to='Personagem.atributo')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pericias', to='Personagem.personagem')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Foto_item')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('peso', models.DecimalField(decimal_places=1, default=0, max_digits=20)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('qualidade', models.CharField(blank=True, max_length=100)),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='Personagem.personagem')),
            ],
        ),
        migrations.CreateModel(
            name='Defesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(blank=True, max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('atributo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defesas', to='Personagem.atributo')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defesas', to='Personagem.personagem')),
            ],
        ),
        migrations.AddField(
            model_name='atributo',
            name='personagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='Personagem.personagem'),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('barra', models.BooleanField(default=False)),
                ('cor', models.CharField(default='#FF0000', max_length=7)),
                ('valor_max', models.PositiveIntegerField(default=0)),
                ('valor_atual', models.PositiveIntegerField(default=0)),
                ('valor_temp', models.IntegerField(default=0)),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='Personagem.personagem')),
            ],
        ),
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Personagem.item')),
                ('ataque', models.IntegerField(blank=True, default=0)),
                ('dano', models.CharField(blank=True, default='1d4', max_length=30)),
                ('dano_extra', models.CharField(blank=True, default='0', max_length=30)),
                ('margem_critico', models.CharField(blank=True, default='20', max_length=30)),
                ('critico', models.CharField(blank=True, default='+1d', max_length=30)),
                ('alcance', models.CharField(blank=True, default='Adjacente', max_length=30)),
                ('tipo_dano', models.CharField(blank=True, default='Cortante', max_length=30)),
                ('empunhadura', models.CharField(blank=True, default='Leve', max_length=30)),
                ('grupo', models.ManyToManyField(blank=True, related_name='armas', to='Personagem.grupoarmas')),
                ('modificacoes', models.ManyToManyField(blank=True, related_name='armas', to='Personagem.modificacao')),
            ],
            bases=('Personagem.item',),
        ),
        migrations.CreateModel(
            name='Armadura',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Personagem.item')),
                ('defesa', models.IntegerField(blank=True, default=0)),
                ('modificacoes', models.ManyToManyField(blank=True, related_name='armaduras', to='Personagem.modificacao')),
            ],
            bases=('Personagem.item',),
        ),
    ]
