# Generated by Django 6.0.6 on 2026-06-30 01:53

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personagem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midia', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Mídia_poder')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('custo', models.IntegerField(default=0)),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poderes', to='Personagem.personagem')),
            ],
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('poder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Personagem.poder')),
                ('nivel', models.PositiveIntegerField(default=1)),
                ('execucao', models.CharField(blank=True, default='1 Ação', max_length=30)),
                ('alcance', models.CharField(blank=True, default='Toque', max_length=30)),
                ('alvo_area', models.CharField(blank=True, default='Um Alvo', max_length=30)),
                ('duracao', models.CharField(blank=True, default='Instantânea', max_length=30)),
                ('resistencia', models.CharField(blank=True, default='Nenhuma', max_length=30)),
            ],
            bases=('Personagem.poder',),
        ),
        migrations.CreateModel(
            name='Tecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midia', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Mídia_tecnica')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('mecanica', models.TextField(blank=True)),
                ('limitacoes', models.TextField(blank=True)),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnicas', to='Personagem.personagem')),
            ],
        ),
        migrations.AddField(
            model_name='poder',
            name='tecnica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poderes', to='Personagem.tecnica'),
        ),
        migrations.CreateModel(
            name='Aprimoramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('custo', models.IntegerField(default=0)),
                ('habilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprimoramentos', to='Personagem.habilidade')),
            ],
        ),
    ]
