# Generated by Django 6.0.6 on 2026-06-30 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personagem', '0002_poder_habilidade_tecnica_poder_tecnica_aprimoramento'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('somente_teste', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
