# Generated by Django 6.0.6 on 2026-07-03 15:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personagem', '0003_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Foto_item'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='banner',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='tecnica',
            name='midia',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Mídia_tecnica'),
        ),
    ]
