# Generated by Django 6.0.6 on 2026-07-04 02:17

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personagem', '0004_alter_item_foto_alter_personagem_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atributo',
            name='cor',
            field=models.CharField(default='#FF0000', max_length=7),
        ),
        migrations.AddField(
            model_name='poder',
            name='atributo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poderes', to='Personagem.atributo'),
        ),
        migrations.AlterField(
            model_name='poder',
            name='midia',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Mídia_poder'),
        ),
    ]
