# Generated by Django 6.0.6 on 2026-07-04 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personagem', '0005_atributo_cor_poder_atributo_alter_poder_midia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poder',
            name='atributo',
        ),
        migrations.AddField(
            model_name='poder',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poderes', to='Personagem.status'),
        ),
    ]
