# Generated by Django 6.0.6 on 2026-07-05 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personagem', '0006_remove_poder_atributo_poder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='atributo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status', to='Personagem.atributo'),
        ),
        migrations.AddField(
            model_name='status',
            name='atributo_nivel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='defesa',
            name='atributo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defesas', to='Personagem.atributo'),
        ),
        migrations.AlterField(
            model_name='pericia',
            name='atributo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pericias', to='Personagem.atributo'),
        ),
        migrations.AlterField(
            model_name='poder',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poderes', to='Personagem.status'),
        ),
        migrations.AlterField(
            model_name='poder',
            name='tecnica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poderes', to='Personagem.tecnica'),
        ),
    ]
