# Generated by Django 6.0.6 on 2026-07-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personagem', '0007_status_atributo_status_atributo_nivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='peso_atual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='personagem',
            name='peso_maximo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poder',
            name='tag',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
