# Generated by Django 6.0.6 on 2026-07-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personagem', '0009_personagem_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributo',
            name='valor',
            field=models.IntegerField(default=0),
        ),
    ]
