# Generated by Django 6.0.6 on 2026-07-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personagem', '0010_alter_atributo_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pericia',
            name='treinamento',
            field=models.IntegerField(default=0),
        ),
    ]
