# Generated by Django 6.0.6 on 2026-07-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personagem', '0011_alter_pericia_treinamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pericia',
            name='somar_atributo',
            field=models.BooleanField(default=False),
        ),
    ]
