# Generated by Django 6.0.6 on 2026-07-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personagem', '0012_pericia_somar_atributo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='classe1',
            field=models.CharField(default='combatente', max_length=40),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='classe2',
            field=models.CharField(default='combatente', max_length=40),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='classe3',
            field=models.CharField(default='combatente', max_length=40),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='classe4',
            field=models.CharField(default='combatente', max_length=40),
        ),
    ]
