# Generated by Django 6.0.6 on 2026-07-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personagem', '0013_alter_personagem_classe1_alter_personagem_classe2_and_more'),
        ('Sistema', '0001_initial'),
    ]

    operations = [
        # AUDIT FIX: a ordem original (DeleteModel antes dos AlterField que
        # ainda apontavam para os models sendo deletados) fazia esta
        # migration falhar com "AttributeError: 'ManyToManyField' object
        # has no attribute 'm2m_reverse_field_name'" ao ser aplicada em um
        # banco novo/limpo — confirmado rodando `migrate` do zero contra
        # um Postgres descartável. Django precisa resolver o M2M antigo
        # (que apontava para Personagem.GrupoArmas/Personagem.Modificacao)
        # para poder migrar a tabela through para o novo alvo
        # (Sistema.GrupoArmas/Sistema.Modificacao) — isso só é possível se
        # o model antigo ainda existir no estado da migration nesse ponto.
        # Reordenar para primeiro repontar os campos e só depois apagar os
        # models antigos resolve isso sem mudar o estado final do schema
        # (idêntico ao original). Como esta migration já está marcada
        # como aplicada em qualquer ambiente que já rodou `migrate` com
        # sucesso antes (Django não reexecuta migrations já registradas em
        # `django_migrations`), esta correção não afeta bancos existentes
        # — só corrige a aplicação em bancos novos (dev local, CI, banco
        # de testes do `manage.py test`, disaster recovery).
        migrations.AlterField(
            model_name='arma',
            name='grupo',
            field=models.ManyToManyField(blank=True, related_name='armas', to='Sistema.GrupoArmas'),
        ),
        migrations.AlterField(
            model_name='arma',
            name='modificacoes',
            field=models.ManyToManyField(blank=True, related_name='armas', to='Sistema.Modificacao'),
        ),
        migrations.AlterField(
            model_name='armadura',
            name='modificacoes',
            field=models.ManyToManyField(blank=True, related_name='armaduras', to='Sistema.Modificacao'),
        ),
        migrations.DeleteModel(
            name='GrupoArmas',
        ),
        migrations.DeleteModel(
            name='Modificacao',
        ),
    ]
