# Generated by Django 6.0.6 on 2026-07-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personagem', '0014_delete_grupoarmas_delete_modificacao_and_more'),
        ('Sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='grupo',
            field=models.ManyToManyField(blank=True, related_name='armas', to='Sistema.GrupoArmas'),
        ),
        migrations.AlterField(
            model_name='arma',
            name='modificacoes',
            field=models.ManyToManyField(blank=True, related_name='armas', to='Sistema.Modificacao'),
        ),
        migrations.AlterField(
            model_name='armadura',
            name='modificacoes',
            field=models.ManyToManyField(blank=True, related_name='armaduras', to='Sistema.Modificacao'),
        ),
    ]
