# Generated by Django 6.0.6 on 2026-08-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personagem', '0015_alter_arma_grupo_alter_arma_modificacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arma',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='status',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='status',
            name='sub_status',
            field=models.BooleanField(default=False),
        ),
    ]
