# Generated by Django 6.0.6 on 2026-08-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personagem', '0016_arma_ordem_status_ordem_status_sub_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='consumivel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
