# Generated by Django 6.0.6 on 2026-08-12 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personagem', '0017_item_consumivel_item_quantidade'),
        ('Sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='sistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personagens', to='Sistema.sistema'),
        ),
    ]
