# Generated by Django 6.0.7 on 2026-09-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personagem', '0018_personagem_sistema'),
        ('Sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='sistemas',
            field=models.ManyToManyField(blank=True, related_name='personagens_bibliotecas', to='Sistema.sistema'),
        ),
    ]
