# Generated by Django 6.0.7 on 2026-09-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personagem', '0020_migrar_sistema_para_sistemas'),
    ]

    operations = [
        migrations.AddField(
            model_name='atributo',
            name='versao',
            field=models.PositiveBigIntegerField(db_default=1, default=1, editable=False),
        ),
        migrations.AddField(
            model_name='bonus',
            name='versao',
            field=models.PositiveBigIntegerField(db_default=1, default=1, editable=False),
        ),
        migrations.AddField(
            model_name='defesa',
            name='versao',
            field=models.PositiveBigIntegerField(db_default=1, default=1, editable=False),
        ),
        migrations.AddField(
            model_name='personagem',
            name='versao',
            field=models.PositiveBigIntegerField(db_default=1, default=1, editable=False),
        ),
        migrations.AddField(
            model_name='status',
            name='versao',
            field=models.PositiveBigIntegerField(db_default=1, default=1, editable=False),
        ),
    ]
