# Generated by Django 6.0.7 on 2026-09-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Personagem", "0021_versao_sincronizacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="vendas",
            field=models.BooleanField(default=False),
        ),
    ]
