# Generated by Django 6.0.7 on 2026-09-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personagem', '0023_defesa_destaque_defesa_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='peso_ajuste_manual',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='personagem',
            name='peso_multiplica_quantidade',
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
