# Generated by Django 6.0.7 on 2026-09-22 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Personagem", "0024_peso_inventario_config"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="aprimoramento",
            name="valor_final",
            field=models.IntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name="bonus",
            name="expira_em",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="bonus",
            name="origem_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bonus_como_origem",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="bonus",
            name="origem_object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bonus",
            name="tipo_origem",
            field=models.CharField(
                choices=[("manual", "Manual"), ("entidade", "Entidade")],
                db_default="manual",
                default="manual",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="valor_final",
            field=models.IntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name="poder",
            name="valor_final",
            field=models.IntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name="tecnica",
            name="valor_final",
            field=models.IntegerField(db_default=0, default=0),
        ),
        migrations.AddIndex(
            model_name="bonus",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="Personagem__content_6f6684_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bonus",
            index=models.Index(
                fields=["origem_content_type", "origem_object_id"],
                name="Personagem__origem__6ba7a4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bonus",
            index=models.Index(
                fields=["expira_em"], name="Personagem__expira__c689eb_idx"
            ),
        ),
    ]
