# Generated by Django 6.0.7 on 2026-09-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Personagem", "0026_unificar_bonus_heranca"),
    ]

    operations = [
        migrations.AddField(
            model_name="pericia",
            name="ordem",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
