# Generated by Django 6.0.7 on 2026-09-23 22:30

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Personagem", "0027_pericia_ordem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PoderUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "midia",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, verbose_name="Mídia_poder"
                    ),
                ),
                ("tag", models.CharField(blank=True, max_length=100)),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("custo", models.IntegerField(default=0)),
                ("valor_final", models.IntegerField(db_default=0, default=0)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poderes_usuario",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="personagem",
            name="poderes_usuario",
            field=models.ManyToManyField(
                blank=True, related_name="personagens", to="Personagem.poderusuario"
            ),
        ),
    ]
