# Generated by Django 6.0.7 on 2026-09-24 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Personagem", "0028_poder_usuario"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="BonusFornecido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("nome", models.CharField(max_length=100)),
                ("valor", models.IntegerField(default=0)),
                ("descricao", models.CharField(blank=True, default="", max_length=255)),
                ("ordem", models.PositiveIntegerField(default=0)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["ordem", "id"],
            },
        ),
        migrations.AddField(
            model_name="bonus",
            name="origem_fornecido",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referencias",
                to="Personagem.bonusfornecido",
            ),
        ),
        migrations.AddIndex(
            model_name="bonusfornecido",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="Personagem__content_970416_idx",
            ),
        ),
    ]
