# Generated by Django 6.0.7 on 2026-09-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Personagem", "0029_bonus_fornecido"),
    ]

    operations = [
        migrations.AddField(
            model_name="personagem",
            name="xp",
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
    ]
