# Generated by Django 6.0.7 on 2026-09-25 19:53

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personagem', '0030_personagem_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='fundo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Fundo'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='tema',
            field=models.JSONField(blank=True, db_default={}, default=dict),
        ),
    ]
