"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import cloudinary
from dotenv import load_dotenv

from datetime import timedelta

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# AUDIT FIX (crítico): sem isso, se a variável de ambiente SECRET_KEY não
# estiver definida, o Django sobe silenciosamente com SECRET_KEY=None, o
# que quebra assinatura de sessão/CSRF de forma imprevisível e pode
# mascarar um deploy mal configurado. Falhar cedo e alto é mais seguro do
# que rodar em produção sem uma SECRET_KEY real.
if not SECRET_KEY:
    raise RuntimeError(
        "A variável de ambiente SECRET_KEY não está definida. Configure-a "
        "no .env (local) ou nas variáveis de ambiente do serviço de "
        "deploy antes de iniciar a aplicação."
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG") == "True"

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "tccrpg.onrender.com",
    "nevezxy.com.br",
    "www.nevezxy.com.br",
    ]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'rest_framework',
    'corsheaders',
    "cloudinary",
    "cloudinary_storage",
    "drf_spectacular",
    
    # AUDIT FIX (crítico): necessário para permitir revogar refresh tokens
    # (logout real, resposta a vazamento de token, etc.). Antes,
    # REFRESH_TOKEN_LIFETIME=3650 dias sem blacklist significava que um
    # refresh token vazado era válido por até 10 anos e não podia ser
    # invalidado de forma alguma.
    # IMPORTANTE (pendência operacional): esta app tem tabelas próprias —
    # rode `python manage.py migrate token_blacklist` antes do deploy.
    "rest_framework_simplejwt.token_blacklist",

    'Personagem',
    'Usuario',
    'Campanha',
    'Sistema',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    "corsheaders.middleware.CorsMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    "whitenoise.middleware.WhiteNoiseMiddleware",
]

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": ("rest_framework_simplejwt.authentication.JWTAuthentication",),

    # AUDIT FIX (crítico): o padrão anterior era AllowAny — qualquer view
    # nova criada no projeto (ou uma existente que por descuido perdesse
    # seu @permission_classes) ficaria PÚBLICA por padrão. As views atuais
    # quase todas já decoram explicitamente com IsAuthenticated, então
    # este é o comportamento real esperado — só faltava torná-lo o padrão
    # seguro. Os endpoints deliberadamente públicos (registro, login,
    # refresh, schema/docs) agora declaram AllowAny explicitamente — ver
    # Usuario/views.py, Usuario/urls.py e app/urls.py.
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),

    # AUDIT FIX (alto): sem throttling, login/registro ficam abertos a
    # força bruta/credential stuffing sem limite de taxa. Ajuste as taxas
    # conforme o volume real de uso.
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "60/min",
        "user": "300/min",
    },
}

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
'''

DATABASES = {
    "default": dj_database_url.parse(
        os.getenv("DATABASE_URL"),
        conn_max_age=600,
        ssl_require=True,
    )
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:5173",
    "http://localhost:5173",
    "http://localhost:5500",
    "https://tccrpg.onrender.com",
    "https://nevezxy.com.br",
    "https://www.nevezxy.com.br",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:5500",
    "https://tccrpg.netlify.app",
    "https://nevezxy.com.br",
    "https://www.nevezxy.com.br",
    
]

cloudinary.config(
    cloud_name=os.getenv("CLOUDINARY_CLOUD_NAME"),
    api_key=os.getenv("CLOUDINARY_API_KEY"),
    api_secret=os.getenv("CLOUDINARY_API_SECRET"),
    secure=True,
)

SPECTACULAR_SETTINGS = {
    "TITLE": "API RPG",
    "DESCRIPTION": "Documentação da API do sistema de RPG.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SERVERS": [
        {
            "url": "http://127.0.0.1:8000",
            "description": "Servidor Local",
        }
    ],
}

AUTH_USER_MODEL = "Usuario.Usuario"

# AUDIT FIX (crítico): antes, ACCESS_TOKEN_LIFETIME=365 HORAS (~15 dias)
# e REFRESH_TOKEN_LIFETIME=3650 DIAS (10 anos), com ROTATE_REFRESH_TOKENS e
# BLACKLIST_AFTER_ROTATION desligados. Um token vazado (access ou refresh)
# continuava válido por anos e não existia NENHUMA forma de revogá-lo. Os
# valores abaixo são bem mais conservadores; ajuste conforme a UX
# desejada, mas evite voltar a usar prazos de anos.
SIMPLE_JWT = {

    "ACCESS_TOKEN_LIFETIME": timedelta(hours=8),

    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),

    "ROTATE_REFRESH_TOKENS": True,

    "BLACKLIST_AFTER_ROTATION": True,
}