# Generated by Django 6.0.7 on 2026-09-23 22:30

import Usuario.models
import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Usuario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="banner",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, verbose_name="Banner"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="cor_perfil",
            field=models.CharField(
                blank=True,
                default="",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9a-fA-F]{6}$", "Use uma cor no formato #RRGGBB."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="data_atualizacao",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="descricao",
            field=models.TextField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="usuario",
            name="links_sociais",
            field=models.JSONField(
                blank=True,
                default=list,
                validators=[Usuario.models.validar_links_sociais],
            ),
        ),
    ]
