# Generated by Django 6.0.6 on 2026-07-23 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='Sistema.sistema')),
            ],
        ),
        migrations.CreateModel(
            name='PoderSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('custo', models.IntegerField(default=0)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poderes', to='Sistema.sistema')),
            ],
        ),
        migrations.CreateModel(
            name='Modificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('custo', models.IntegerField(default=1)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modificacoes', to='Sistema.sistema')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('peso', models.DecimalField(decimal_places=1, default=0, max_digits=20)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('qualidade', models.CharField(blank=True, max_length=100)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='Sistema.sistema')),
            ],
        ),
        migrations.CreateModel(
            name='HabilidadeSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('custo', models.IntegerField(default=0)),
                ('nivel', models.PositiveIntegerField(default=1)),
                ('execucao', models.CharField(blank=True, default='1 Ação', max_length=30)),
                ('alcance', models.CharField(blank=True, default='Toque', max_length=30)),
                ('alvo_area', models.CharField(blank=True, default='Um Alvo', max_length=30)),
                ('duracao', models.CharField(blank=True, default='Instantânea', max_length=30)),
                ('resistencia', models.CharField(blank=True, default='Nenhuma', max_length=30)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='Sistema.sistema')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoArmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('comum', models.TextField(blank=True)),
                ('trabalhado', models.TextField(blank=True)),
                ('obra_prima', models.TextField(blank=True)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_armas', to='Sistema.sistema')),
            ],
        ),
        migrations.CreateModel(
            name='ArmaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('peso', models.DecimalField(decimal_places=1, default=0, max_digits=20)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('qualidade', models.CharField(blank=True, max_length=100)),
                ('ataque', models.IntegerField(blank=True, default=0)),
                ('dano', models.CharField(blank=True, default='1d4', max_length=30)),
                ('dano_extra', models.CharField(blank=True, default='0', max_length=30)),
                ('margem_critico', models.CharField(blank=True, default='20', max_length=30)),
                ('critico', models.CharField(blank=True, default='+1d', max_length=30)),
                ('alcance', models.CharField(blank=True, default='Adjacente', max_length=30)),
                ('tipo_dano', models.CharField(blank=True, default='Cortante', max_length=30)),
                ('empunhadura', models.CharField(blank=True, default='Leve', max_length=30)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armas', to='Sistema.sistema')),
            ],
        ),
        migrations.CreateModel(
            name='ArmaduraSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('peso', models.DecimalField(decimal_places=1, default=0, max_digits=20)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('qualidade', models.CharField(blank=True, max_length=100)),
                ('defesa', models.IntegerField(blank=True, default=0)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armaduras', to='Sistema.sistema')),
            ],
        ),
    ]
