# Generated by Django 6.0.7 on 2026-09-15 14:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Sistema", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="armadurasistema",
            name="foto",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="Foto"
            ),
        ),
        migrations.AddField(
            model_name="armasistema",
            name="foto",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="Foto"
            ),
        ),
        migrations.AddField(
            model_name="habilidadesistema",
            name="midia",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="Mídia"
            ),
        ),
        migrations.AddField(
            model_name="itemsistema",
            name="foto",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="Foto"
            ),
        ),
        migrations.AddField(
            model_name="podersistema",
            name="midia",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="Mídia"
            ),
        ),
    ]
