# Generated by Django 6.0.6 on 2026-07-12 18:20

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Personagem', '0012_pericia_somar_atributo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Banner')),
                ('nome', models.CharField(db_index=True, max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('anotacoes', models.TextField(blank=True)),
                ('codigo', models.CharField(db_index=True, editable=False, max_length=5, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('jogadores', models.ManyToManyField(blank=True, related_name='campanhas', to=settings.AUTH_USER_MODEL)),
                ('mestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanhas_criadas', to=settings.AUTH_USER_MODEL)),
                ('personagens', models.ManyToManyField(blank=True, related_name='campanhas', to='Personagem.personagem')),
            ],
        ),
    ]
