# Generated by Django 6.0.6 on 2026-07-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campanha', '0002_local_mapa_missao_nota_npc_organizacao_and_more'),
        ('Personagem', '0012_pericia_somar_atributo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organizacao',
            name='organizacao_um_unico_lider',
        ),
        migrations.AddConstraint(
            model_name='organizacao',
            constraint=models.CheckConstraint(condition=models.Q(('lider_personagem__isnull', False), ('lider_npc__isnull', False), _negated=True), name='organizacao_um_unico_lider'),
        ),
    ]
