# Generated by Django 6.0.6 on 2026-07-23 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campanha', '0003_remove_organizacao_organizacao_um_unico_lider_and_more'),
        ('Personagem', '0012_pericia_somar_atributo'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='personagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_como_personagem', to='Personagem.personagem'),
        ),
    ]
