# Generated by Django 6.0.6 on 2026-07-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campanha', '0004_nota_personagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='ficha',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
