# Generated by Django 6.0.7 on 2026-09-03 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campanha', '0006_campanha_sistema'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='conteudo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='local',
            name='conteudo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mapa',
            name='conteudo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='missao',
            name='conteudo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='conteudo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='conteudo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sessao',
            name='conteudo',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastas', to='Campanha.campanha')),
                ('pasta_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subpastas', to='Campanha.pasta')),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='pasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='Campanha.pasta'),
        ),
        migrations.AddField(
            model_name='local',
            name='pasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locais', to='Campanha.pasta'),
        ),
        migrations.AddField(
            model_name='mapa',
            name='pasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapas', to='Campanha.pasta'),
        ),
        migrations.AddField(
            model_name='missao',
            name='pasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missoes', to='Campanha.pasta'),
        ),
        migrations.AddField(
            model_name='npc',
            name='pasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npcs', to='Campanha.pasta'),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='pasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizacoes', to='Campanha.pasta'),
        ),
        migrations.AddField(
            model_name='sessao',
            name='pasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes', to='Campanha.pasta'),
        ),
        migrations.CreateModel(
            name='TipoConexao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('inverso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_inversos', to='Campanha.tipoconexao')),
            ],
            options={
                'verbose_name': 'Tipo de Conexão',
                'verbose_name_plural': 'Tipos de Conexão',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Conexao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade1_id', models.PositiveIntegerField()),
                ('entidade2_id', models.PositiveIntegerField()),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexoes', to='Campanha.campanha')),
                ('entidade1_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('entidade2_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conexoes', to='Campanha.tipoconexao')),
            ],
            options={
                'verbose_name': 'Conexão',
                'verbose_name_plural': 'Conexões',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='pasta',
            index=models.Index(fields=['campanha', 'pasta_pai'], name='Campanha_pa_campanh_531859_idx'),
        ),
        migrations.AddConstraint(
            model_name='pasta',
            constraint=models.UniqueConstraint(fields=('campanha', 'pasta_pai', 'nome'), name='pasta_nome_unico_por_pai'),
        ),
        migrations.AddIndex(
            model_name='conexao',
            index=models.Index(fields=['campanha'], name='Campanha_co_campanh_5f11df_idx'),
        ),
        migrations.AddIndex(
            model_name='conexao',
            index=models.Index(fields=['entidade1_tipo', 'entidade1_id'], name='Campanha_co_entidad_c15bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='conexao',
            index=models.Index(fields=['entidade2_tipo', 'entidade2_id'], name='Campanha_co_entidad_70a599_idx'),
        ),
        migrations.AddConstraint(
            model_name='conexao',
            constraint=models.CheckConstraint(condition=models.Q(('entidade1_tipo', models.F('entidade2_tipo')), ('entidade1_id', models.F('entidade2_id')), _negated=True), name='conexao_entidades_diferentes'),
        ),
        migrations.AddConstraint(
            model_name='conexao',
            constraint=models.UniqueConstraint(fields=('entidade1_tipo', 'entidade1_id', 'entidade2_tipo', 'entidade2_id', 'tipo'), name='conexao_unica_por_tipo'),
        ),
    ]
