# Generated by Django 6.0.7 on 2026-09-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campanha', '0009_remove_campos_e_modelos_antigos'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='local',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mapa',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='missao',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='npc',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pasta',
            name='cor',
            field=models.CharField(blank=True, help_text="Cor hexadecimal (ex.: '#FF0000').", max_length=7),
        ),
        migrations.AddField(
            model_name='pasta',
            name='editavel_para_jogadores',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pasta',
            name='icone',
            field=models.CharField(blank=True, help_text="Nome do ícone (ex.: 'folder', 'folder-open', 'file-text').", max_length=100),
        ),
        migrations.AddField(
            model_name='pasta',
            name='visivel_para_jogadores',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sessao',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
