# Generated by Django 6.0.7 on 2026-09-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campanha', '0010_evento_ordem_local_ordem_mapa_ordem_missao_ordem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='cor',
            field=models.CharField(blank=True, help_text="Cor hexadecimal (ex.: '#FF0000').", max_length=7),
        ),
        migrations.AddField(
            model_name='evento',
            name='icone',
            field=models.CharField(blank=True, help_text="Nome do ícone lucide (ex.: 'user', 'map-pin').", max_length=100),
        ),
        migrations.AddField(
            model_name='local',
            name='cor',
            field=models.CharField(blank=True, help_text="Cor hexadecimal (ex.: '#FF0000').", max_length=7),
        ),
        migrations.AddField(
            model_name='local',
            name='icone',
            field=models.CharField(blank=True, help_text="Nome do ícone lucide (ex.: 'user', 'map-pin').", max_length=100),
        ),
        migrations.AddField(
            model_name='mapa',
            name='cor',
            field=models.CharField(blank=True, help_text="Cor hexadecimal (ex.: '#FF0000').", max_length=7),
        ),
        migrations.AddField(
            model_name='mapa',
            name='icone',
            field=models.CharField(blank=True, help_text="Nome do ícone lucide (ex.: 'user', 'map-pin').", max_length=100),
        ),
        migrations.AddField(
            model_name='missao',
            name='cor',
            field=models.CharField(blank=True, help_text="Cor hexadecimal (ex.: '#FF0000').", max_length=7),
        ),
        migrations.AddField(
            model_name='missao',
            name='icone',
            field=models.CharField(blank=True, help_text="Nome do ícone lucide (ex.: 'user', 'map-pin').", max_length=100),
        ),
        migrations.AddField(
            model_name='npc',
            name='cor',
            field=models.CharField(blank=True, help_text="Cor hexadecimal (ex.: '#FF0000').", max_length=7),
        ),
        migrations.AddField(
            model_name='npc',
            name='icone',
            field=models.CharField(blank=True, help_text="Nome do ícone lucide (ex.: 'user', 'map-pin').", max_length=100),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='cor',
            field=models.CharField(blank=True, help_text="Cor hexadecimal (ex.: '#FF0000').", max_length=7),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='icone',
            field=models.CharField(blank=True, help_text="Nome do ícone lucide (ex.: 'user', 'map-pin').", max_length=100),
        ),
        migrations.AddField(
            model_name='sessao',
            name='cor',
            field=models.CharField(blank=True, help_text="Cor hexadecimal (ex.: '#FF0000').", max_length=7),
        ),
        migrations.AddField(
            model_name='sessao',
            name='icone',
            field=models.CharField(blank=True, help_text="Nome do ícone lucide (ex.: 'user', 'map-pin').", max_length=100),
        ),
    ]
