# Generated by Django 6.0.7 on 2026-09-15 14:35

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Campanha", "0014_ficha_preset"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArmaCampanha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(db_index=True, max_length=200)),
                ("conteudo", models.TextField(blank=True)),
                (
                    "icone",
                    models.CharField(
                        blank=True,
                        help_text="Nome do ícone lucide (ex.: 'user', 'map-pin').",
                        max_length=100,
                    ),
                ),
                (
                    "cor",
                    models.CharField(
                        blank=True,
                        help_text="Cor hexadecimal (ex.: '#FF0000').",
                        max_length=7,
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("visivel_para_jogadores", models.BooleanField(default=True)),
                ("editavel_para_jogadores", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "foto",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="Foto"
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                (
                    "peso",
                    models.DecimalField(decimal_places=1, default=0, max_digits=20),
                ),
                (
                    "valor",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("qualidade", models.CharField(blank=True, max_length=100)),
                ("ataque", models.IntegerField(blank=True, default=0)),
                ("dano", models.CharField(blank=True, default="1d4", max_length=30)),
                (
                    "dano_extra",
                    models.CharField(blank=True, default="0", max_length=30),
                ),
                (
                    "margem_critico",
                    models.CharField(blank=True, default="20", max_length=30),
                ),
                ("critico", models.CharField(blank=True, default="+1d", max_length=30)),
                (
                    "alcance",
                    models.CharField(blank=True, default="Adjacente", max_length=30),
                ),
                (
                    "tipo_dano",
                    models.CharField(blank=True, default="Cortante", max_length=30),
                ),
                (
                    "empunhadura",
                    models.CharField(blank=True, default="Leve", max_length=30),
                ),
                (
                    "campanha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="armas_campanha",
                        to="Campanha.campanha",
                    ),
                ),
                (
                    "pasta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="armas_campanha",
                        to="Campanha.pasta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arma da campanha",
                "verbose_name_plural": "Armas da campanha",
                "ordering": ["ordem", "nome"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ArmaduraCampanha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(db_index=True, max_length=200)),
                ("conteudo", models.TextField(blank=True)),
                (
                    "icone",
                    models.CharField(
                        blank=True,
                        help_text="Nome do ícone lucide (ex.: 'user', 'map-pin').",
                        max_length=100,
                    ),
                ),
                (
                    "cor",
                    models.CharField(
                        blank=True,
                        help_text="Cor hexadecimal (ex.: '#FF0000').",
                        max_length=7,
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("visivel_para_jogadores", models.BooleanField(default=True)),
                ("editavel_para_jogadores", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "foto",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="Foto"
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                (
                    "peso",
                    models.DecimalField(decimal_places=1, default=0, max_digits=20),
                ),
                (
                    "valor",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("qualidade", models.CharField(blank=True, max_length=100)),
                ("defesa", models.IntegerField(blank=True, default=0)),
                (
                    "campanha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="armaduras_campanha",
                        to="Campanha.campanha",
                    ),
                ),
                (
                    "pasta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="armaduras_campanha",
                        to="Campanha.pasta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Armadura da campanha",
                "verbose_name_plural": "Armaduras da campanha",
                "ordering": ["ordem", "nome"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ItemCampanha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(db_index=True, max_length=200)),
                ("conteudo", models.TextField(blank=True)),
                (
                    "icone",
                    models.CharField(
                        blank=True,
                        help_text="Nome do ícone lucide (ex.: 'user', 'map-pin').",
                        max_length=100,
                    ),
                ),
                (
                    "cor",
                    models.CharField(
                        blank=True,
                        help_text="Cor hexadecimal (ex.: '#FF0000').",
                        max_length=7,
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("visivel_para_jogadores", models.BooleanField(default=True)),
                ("editavel_para_jogadores", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "foto",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="Foto"
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                (
                    "peso",
                    models.DecimalField(decimal_places=1, default=0, max_digits=20),
                ),
                (
                    "valor",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("qualidade", models.CharField(blank=True, max_length=100)),
                (
                    "campanha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens_campanha",
                        to="Campanha.campanha",
                    ),
                ),
                (
                    "pasta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="itens_campanha",
                        to="Campanha.pasta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item da campanha",
                "verbose_name_plural": "Itens da campanha",
                "ordering": ["ordem", "nome"],
                "abstract": False,
            },
        ),
    ]
