# Generated by Django 6.0.7 on 2026-09-15 14:49

import Campanha.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Campanha", "0015_equipamentos_campanha"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaLoja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                (
                    "icone",
                    models.CharField(
                        blank=True,
                        help_text="Nome do ícone lucide (ex.: 'sword').",
                        max_length=100,
                    ),
                ),
                (
                    "cor",
                    models.CharField(
                        blank=True,
                        help_text="Cor hexadecimal (ex.: '#FF0000').",
                        max_length=7,
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("visivel_para_jogadores", models.BooleanField(default=True)),
                ("rotacao_ativa", models.BooleanField(default=False)),
                (
                    "rotacao_quantidade",
                    models.PositiveIntegerField(
                        default=3, help_text="Quantos produtos ficam à mostra por vez."
                    ),
                ),
                (
                    "rotacao_intervalo_minutos",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="De quanto em quanto tempo a seleção troca.",
                    ),
                ),
                (
                    "rotacao_metodo",
                    models.CharField(
                        choices=[("aleatorio", "Aleatório"), ("ordem", "Por ordem")],
                        default="aleatorio",
                        max_length=20,
                    ),
                ),
                (
                    "rotacao_inicio",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "rotacao_semente",
                    models.PositiveBigIntegerField(
                        default=Campanha.models._semente_aleatoria
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "campanha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorias_loja",
                        to="Campanha.campanha",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria da loja",
                "verbose_name_plural": "Categorias da loja",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.CreateModel(
            name="ProdutoLoja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "preco",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "quantidade_disponivel",
                    models.PositiveIntegerField(
                        blank=True, help_text="Vazio = estoque ilimitado.", null=True
                    ),
                ),
                ("disponivel", models.BooleanField(default=True)),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "campanha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produtos_loja",
                        to="Campanha.campanha",
                    ),
                ),
                (
                    "categorias",
                    models.ManyToManyField(
                        blank=True, related_name="produtos", to="Campanha.categorialoja"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto da loja",
                "verbose_name_plural": "Produtos da loja",
                "ordering": ["ordem", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="categorialoja",
            index=models.Index(
                fields=["campanha", "ordem"], name="Campanha_ca_campanh_d36586_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="categorialoja",
            constraint=models.UniqueConstraint(
                fields=("campanha", "nome"),
                name="categoria_loja_nome_unico_por_campanha",
            ),
        ),
        migrations.AddIndex(
            model_name="produtoloja",
            index=models.Index(
                fields=["campanha", "disponivel"], name="Campanha_pr_campanh_208336_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="produtoloja",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="Campanha_pr_content_9553dd_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="produtoloja",
            constraint=models.UniqueConstraint(
                fields=("campanha", "content_type", "object_id"),
                name="produto_loja_unico_por_campanha",
            ),
        ),
    ]
