# Generated by Django 6.0.7 on 2026-09-15 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Campanha", "0016_loja"),
        ("Personagem", "0021_versao_sincronizacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransacaoLoja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("loja", "Loja da campanha"),
                            ("comercio_livre", "Comércio livre"),
                        ],
                        default="loja",
                        max_length=20,
                    ),
                ),
                ("nome_item", models.CharField(max_length=200)),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("quantidade", models.PositiveIntegerField(default=1)),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "chave_idempotencia",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "campanha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transacoes_loja",
                        to="Campanha.campanha",
                    ),
                ),
                (
                    "comprador_personagem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compras",
                        to="Personagem.personagem",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transacoes",
                        to="Campanha.produtoloja",
                    ),
                ),
                (
                    "vendedor_personagem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendas",
                        to="Personagem.personagem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transação da loja",
                "verbose_name_plural": "Transações da loja",
                "ordering": ["-criado_em", "-id"],
                "indexes": [
                    models.Index(
                        fields=["campanha", "-criado_em"],
                        name="Campanha_tr_campanh_ee1abe_idx",
                    )
                ],
            },
        ),
    ]
