# Generated by Django 6.0.7 on 2026-09-15 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Campanha", "0017_transacao_loja"),
        ("Personagem", "0022_comercio_livre"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnuncioComercioLivre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=1)),
                (
                    "preco",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "campanha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anuncios",
                        to="Campanha.campanha",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anuncios",
                        to="Personagem.item",
                    ),
                ),
                (
                    "vendedor_personagem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anuncios",
                        to="Personagem.personagem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anúncio do comércio livre",
                "verbose_name_plural": "Anúncios do comércio livre",
                "ordering": ["-criado_em", "-id"],
            },
        ),
        migrations.AddField(
            model_name="transacaoloja",
            name="anuncio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transacoes",
                to="Campanha.anunciocomerciolivre",
            ),
        ),
        migrations.AddIndex(
            model_name="anunciocomerciolivre",
            index=models.Index(
                fields=["campanha", "ativo"], name="Campanha_an_campanh_176ba2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="anunciocomerciolivre",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ativo", True)),
                fields=("item",),
                name="anuncio_ativo_unico_por_item",
            ),
        ),
    ]
