# Generated by Django 6.0.7 on 2026-09-15 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Campanha", "0018_comercio_livre"),
        ("Personagem", "0022_comercio_livre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anunciocomerciolivre",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="anuncios",
                to="Personagem.item",
            ),
        ),
    ]
