# Generated by Django 6.0.7 on 2026-09-15 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Campanha", "0019_anuncio_item_set_null"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="armacampanha",
            options={
                "ordering": ["ordem", "nome"],
                "verbose_name": "Arma",
                "verbose_name_plural": "Armas",
            },
        ),
        migrations.AlterModelOptions(
            name="armaduracampanha",
            options={
                "ordering": ["ordem", "nome"],
                "verbose_name": "Armadura",
                "verbose_name_plural": "Armaduras",
            },
        ),
        migrations.AlterModelOptions(
            name="itemcampanha",
            options={
                "ordering": ["ordem", "nome"],
                "verbose_name": "Item",
                "verbose_name_plural": "Itens",
            },
        ),
    ]
