# Generated by Django 6.0.7 on 2026-09-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Campanha", "0020_alter_armacampanha_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="criatura",
            name="ficha",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
