# Generated by Django 6.0.7 on 2026-09-15 23:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campanha', '0021_criatura_ficha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='moderadores',
            field=models.ManyToManyField(blank=True, related_name='campanhas_moderadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
