# Generated by Django 6.0.7 on 2026-09-16 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campanha', '0022_campanha_moderadores'),
        ('Personagem', '0022_comercio_livre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.PositiveBigIntegerField(db_default=1, default=1, editable=False)),
                ('rodada', models.PositiveIntegerField(default=1)),
                ('visivel_para_jogadores', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('campanha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='combate', to='Campanha.campanha')),
            ],
            options={
                'verbose_name': 'Combate',
                'verbose_name_plural': 'Combates',
            },
        ),
        migrations.CreateModel(
            name='ParticipanteCombate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.PositiveBigIntegerField(db_default=1, default=1, editable=False)),
                ('tipo', models.CharField(choices=[('personagem', 'Personagem'), ('npc', 'NPC'), ('criatura', 'Criatura')], max_length=20)),
                ('iniciativa', models.IntegerField(default=0)),
                ('pv_atual', models.PositiveIntegerField(blank=True, null=True)),
                ('pv_max', models.PositiveIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('combate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='Campanha.combate')),
                ('criatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participacoes_combate', to='Campanha.criatura')),
                ('npc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participacoes_combate', to='Campanha.npc')),
                ('personagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participacoes_combate', to='Personagem.personagem')),
            ],
            options={
                'verbose_name': 'Participante de combate',
                'verbose_name_plural': 'Participantes de combate',
                'ordering': ['-iniciativa', 'id'],
            },
        ),
        migrations.AddField(
            model_name='combate',
            name='turno_participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Campanha.participantecombate'),
        ),
        migrations.AddIndex(
            model_name='participantecombate',
            index=models.Index(fields=['combate', '-iniciativa', 'id'], name='Campanha_pa_combate_5995f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='participantecombate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('criatura__isnull', True), ('npc__isnull', True), ('personagem__isnull', False), ('tipo', 'personagem')), models.Q(('criatura__isnull', True), ('npc__isnull', False), ('personagem__isnull', True), ('tipo', 'npc')), models.Q(('criatura__isnull', False), ('npc__isnull', True), ('personagem__isnull', True), ('tipo', 'criatura')), _connector='OR'), name='participante_combate_uma_entidade'),
        ),
    ]
