# Generated by Django 6.0.7 on 2026-09-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campanha', '0023_combate'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='escudo_ordem',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
