# Generated by Django 6.0.7 on 2026-09-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Campanha", "0024_campanha_escudo_ordem"),
    ]

    operations = [
        migrations.AddField(
            model_name="npc",
            name="ocupacao",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="npc",
            name="status_social",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
