# Generated by Django 6.0.7 on 2026-09-19 15:58

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Campanha", "0026_migrar_raca_tendencias_tracos_raciais"),
    ]

    operations = [
        migrations.CreateModel(
            name="PoderCampanha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(db_index=True, max_length=200)),
                ("conteudo", models.TextField(blank=True)),
                (
                    "icone",
                    models.CharField(
                        blank=True,
                        help_text="Nome do ícone lucide (ex.: 'user', 'map-pin').",
                        max_length=100,
                    ),
                ),
                (
                    "cor",
                    models.CharField(
                        blank=True,
                        help_text="Cor hexadecimal (ex.: '#FF0000').",
                        max_length=7,
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("visivel_para_jogadores", models.BooleanField(default=True)),
                ("editavel_para_jogadores", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "midia",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="Mídia"
                    ),
                ),
                ("tag", models.CharField(blank=True, max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("custo", models.IntegerField(default=0)),
                (
                    "campanha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poderes_campanha",
                        to="Campanha.campanha",
                    ),
                ),
                (
                    "pasta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="poderes_campanha",
                        to="Campanha.pasta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Poder",
                "verbose_name_plural": "Poderes",
                "ordering": ["ordem", "nome"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HabilidadeCampanha",
            fields=[
                (
                    "podercampanha_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="Campanha.podercampanha",
                    ),
                ),
                ("nivel", models.PositiveIntegerField(default=1)),
                (
                    "execucao",
                    models.CharField(blank=True, default="1 Ação", max_length=30),
                ),
                (
                    "alcance",
                    models.CharField(blank=True, default="Toque", max_length=30),
                ),
                (
                    "alvo_area",
                    models.CharField(blank=True, default="Um Alvo", max_length=30),
                ),
                (
                    "duracao",
                    models.CharField(blank=True, default="Instantânea", max_length=30),
                ),
                (
                    "resistencia",
                    models.CharField(blank=True, default="Nenhuma", max_length=30),
                ),
            ],
            options={
                "verbose_name": "Habilidade",
                "verbose_name_plural": "Habilidades",
                "ordering": ["ordem", "nome"],
                "abstract": False,
            },
            bases=("Campanha.podercampanha",),
        ),
        migrations.CreateModel(
            name="TecnicaCampanha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(db_index=True, max_length=200)),
                ("conteudo", models.TextField(blank=True)),
                (
                    "icone",
                    models.CharField(
                        blank=True,
                        help_text="Nome do ícone lucide (ex.: 'user', 'map-pin').",
                        max_length=100,
                    ),
                ),
                (
                    "cor",
                    models.CharField(
                        blank=True,
                        help_text="Cor hexadecimal (ex.: '#FF0000').",
                        max_length=7,
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("visivel_para_jogadores", models.BooleanField(default=True)),
                ("editavel_para_jogadores", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "midia",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="Mídia"
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                ("mecanica", models.TextField(blank=True)),
                ("limitacoes", models.TextField(blank=True)),
                (
                    "campanha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tecnicas_campanha",
                        to="Campanha.campanha",
                    ),
                ),
                (
                    "pasta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tecnicas_campanha",
                        to="Campanha.pasta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Técnica",
                "verbose_name_plural": "Técnicas",
                "ordering": ["ordem", "nome"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="podercampanha",
            name="tecnica",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="poderes",
                to="Campanha.tecnicacampanha",
            ),
        ),
        migrations.CreateModel(
            name="AprimoramentoCampanha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=1)),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("custo", models.IntegerField(default=0)),
                (
                    "habilidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aprimoramentos",
                        to="Campanha.habilidadecampanha",
                    ),
                ),
            ],
        ),
    ]
